<a href="https://colab.research.google.com/github/aadhavjawahar-sys/Poker_hand_predictor/blob/main/Decision_tree_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
#Get neccessary import modules for decision tre
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [103]:
#Data sets
url_train = "/poker-hand-testing.data"
url_test = "/poker-hand-training-true.data"

#Training data manipulation
df = pd.read_csv(url_train)

for i in range(1,6):
  for j in range(i+1,6):
    df["S" + str(i) + "==S" + str(j)]= (df["S" + str(i)] == df["S" + str(j)])
    df["C" + str(i) + "==C" + str(j)]= (df["C" + str(i)] == df["C" + str(j)])
  df.drop(columns="S" + str(i),inplace=True)

X_train = df.drop(columns=["CLASS"])
y_train = df["CLASS"]

#Testing data manipulation
df = pd.read_csv(url_test)

for i in range(1,6):
  for j in range(i+1,6):
    df["S" + str(i) + "==S" + str(j)]= (df["S" + str(i)] == df["S" + str(j)])
    df["C" + str(i) + "==C" + str(j)]= (df["C" + str(i)] == df["C" + str(j)])
  df.drop(columns="S" + str(i),inplace=True)

X_test = df.drop(columns=["CLASS"])
y_test = df["CLASS"]

df.head()

,C1,C2,C3,C4,C5,CLASS,S1==S2,C1==C2,S1==S3,C1==C3,...,S2==S4,C2==C4,S2==S5,C2==C5,S3==S4,C3==C4,S3==S5,C3==C5,S4==S5,C4==C5
0,10,11,13,12,1,9,True,False,True,False,...,True,False,True,False,True,False,True,False,True,False
1,11,13,10,12,1,9,True,False,True,False,...,True,False,True,False,True,False,True,False,True,False
2,12,11,13,10,1,9,True,False,True,False,...,True,False,True,False,True,False,True,False,True,False
3,10,11,1,13,12,9,True,False,True,False,...,True,False,True,False,True,False,True,False,True,False
4,1,13,12,11,10,9,True,False,True,False,...,True,False,True,False,True,False,True,False,True,False


In [104]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [105]:
model.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [106]:
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

In [107]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))

[[501209      0      0      0      0      0      0      0      0      0]
 [     0 422498      0      0      0      0      0      0      0      0]
 [     0      0  47622      0      0      0      0      0      0      0]
 [     0      0      0  21121      0      0      0      0      0      0]
 [     0      0      0      0   3885      0      0      0      0      0]
 [     0      0      0      0      0   1996      0      0      0      0]
 [     0      0      0      0      0      0   1424      0      0      0]
 [     0      0      0      0      0      0      0    230      0      0]
 [     0      0      0      0      0      0      0      0     12      0]
 [     0      0      0      0      0      0      0      0      0      3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    501209
           1       1.00      1.00      1.00    422498
           2       1.00      1.00      1.00     47622
           3       1.00      1.00      1.00     2112

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
